### ISSUE TITLE
Pilot

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#1]
Make User Model, News Model, Comments Model  in different files 
Use MongoDB for database and its' functionalities for the same
There are many courses available on the web for mongo, you can refer to the same
Once you have created a database, paste its link in env file with name MONGO_URI
**THE FOLLOWING IS THE SCHEMA FOR USER AND NEWS **

1. User Schema:

- First Name (String)
- Last Name (String)
- Username (String, unique)
- Profile Image (String - URL)
- Email (String)
- Password (String, encrypted)
- isAdmin (Boolean) 
- myUpvotes (Array of User references)
- News[ ] (Array of News references)

2. News Schema:

- Headline (String)
- Location (String - URL)
- Description (String - HTML)
- Tags (String[ ])
- Upvotes Count (Int)
- User (Reference to User)
- Comments[ ] (Array of Comment references)

3. Comments Schema:

- News (Reference to News)
- User (Reference to User)
- Date 
- Comment (String)

**Comment by Jarviss77** [comment]
pls assign sir

**Comment by PranavBansal21** [comment]
claim

**Comment by 0mBudsMan** [comment]
Congrats Jarvis! Do ping on discord if you find any difficulties.

**Comment by Rudreshdabre12** [comment]
claim

**Comment by Harshal5167** [comment]
claim

**Comment by Aryan4884** [comment]
claim

**Comment by parimal-10** [comment]
claim
