### ISSUE TITLE
Implement Multer and Cloudinary for User Image Upload in Registration Controller

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#13]
## Issue Title:
"Implement Multer and Cloudinary for User Image Upload"

### Deadline:
24 hours

### Objective:
Implement Multer middleware to handle file uploads during user registration and utilize Cloudinary to store and retrieve image URLs.

#### Task 1: Multer Middleware
1. **Description:**
   Create a Multer middleware (`multerMiddleware.js`) to handle image file uploads during user registration.

2. **File Handling:**
   - Configure Multer to handle image files.
   - Implement logic to store uploaded image files locally.

#### Task 2: Cloudinary Integration
1. **Description:**
   Integrate Cloudinary into the application to handle image storage and retrieval.

2. **Upload to Cloudinary:**
   - Use the Cloudinary SDK for Node.js to upload image files to Cloudinary.
   - Ensure secure and authenticated communication with the Cloudinary API.

#### Task 3: Update User Registration Controller
1. **Description:**
   Modify the user registration controller (`user.controllers.js`) to handle user images in the form of URLs.

2. **Image URL Handling:**
   - Utilize the Multer middleware to handle file uploads.
   - Use Cloudinary URLs in the user registration process to store image references.

#### Task 4: Integration
1. **Description:**
   Integrate the Multer and Cloudinary middleware into the user registration process.

2. **Middleware Flow:**
   - Ensure the Multer middleware is invoked to handle file uploads.
   - Confirm that Cloudinary is used to store and retrieve image URLs.

### Additional Information:

- Multer will be used for handling file uploads locally.
- Cloudinary will be used for long-term storage and retrieval of image URLs.
- Implement appropriate error handling for unsuccessful file uploads or Cloudinary interactions.

**Comment by Rohit-110** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Xaverick** [comment]
Claim

**Comment by AngadManroy** [comment]
Claim

**Comment by coderatiiita** [comment]
claim

**Comment by Rohit-110** [comment]
@0mBudsMan Sir, Kindly extend the deadline if possible, I need some more time to implement this

**Comment by Vihaan-19** [comment]
@Rohit-110 done

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by Jarviss77** [comment]
cl
