### ISSUE TITLE
Create User Controllers

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#16]
#### Create Endpoints:
- [ ] - Create ```POST /api/users/:userId/upvote``` endpoint for upvoting a user (user auth required).
- [ ] - Create ```GET /api/users/allUsers``` endpoint for retrieving details of all users (user auth required, accessible only by admin users).
- [ ] - Create ```GET /api/users/:userId``` endpoint for retrieving details of a specific user.
- [ ] - Create ```DELETE /api/users/delete/:userId``` endpoint for deleting user details (user auth required, accessible only by admin users).

- Create controllers for each endpoint.
- Ensure user authentication for required endpoints.
- Add authorisation checks where necessary (e.g., isAdmin check for admin-specific endpoints).
- Ensure proper error handling.

**Comment by rnavaneeth992** [comment]
Claim

**Comment by Vihaan-19** [comment]
@rnavaneeth992 Assigned.

**Comment by coderatiiita** [comment]
claim
