### ISSUE TITLE
Create News Controllers

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#17]
### Create Endpoints
- [x]  - `POST /api/scoop/post`: Allow users to post news (auth required)
- [x]   - `POST /api/scoop/:scoopId/upvote`: Upvote a news. (auth required)
- [x]   - `GET /api/scoop/:scoopId`:Get news details.
- [x]  - `DELETE  /api/scoop/delete/:scoopId`: Delete news. (auth required with admin access)
- Create controllers for each endpoint.
- Ensure user authentication for required endpoints. (using the auth middleware
- Add authorisation checks where necessary (using the isAdmin middleware).
- Ensure proper error handling.

**Comment by DikshantK2004** [comment]
Claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Vihaan-19** [comment]
@DikshantK2004 Assigned.

**Comment by coderatiiita** [comment]
claim

**Comment by coderatiiita** [comment]
claim
