### ISSUE TITLE
Implement Authentication Routes

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#2]
## 1. Register New User Endpoint

- **Route:** `POST /api/auth/register`
- **Description:** Implement a route to register a new user.

**Requirements:**
- [ ] Accept user details (refer User model) (e.g., username, email, password, etc).
- [ ] Validate input data.
- [ ] Hash the password securely.
- [ ] Save user information to the database.
- [ ] Return appropriate response and handle errors.

---

## 2. Login User Endpoint

- **Route:** `POST /api/auth/login`
- **Description:** Implement a route to authenticate and log in a user.

**Requirements:**
- [ ] Accept login credentials (refer User model) (e.g., username/email and password, etc).
- [ ] Validate input data.
- [ ] Verify user credentials against stored data.
- [ ] Generate and return an authentication token upon successful login.
- [ ] Implement error handling for unsuccessful login attempts.

**Additional Guidelines:**
- Include comprehensive error messages to aid debugging and user feedback.
- Ensure compatibility with the existing user database.

**Note:** This issue encompasses the initial implementation of user registration and login routes. Future enhancements, such as password recovery and account management, can be addressed in separate issues.

**Comment by PranavBansal21** [comment]
claim

**Comment by Vihaan-19** [comment]
@PranavBansal21 Assigned!

**Comment by amanrubey** [comment]
claim

**Comment by chandra1899** [comment]
claim

**Comment by coderatiiita** [comment]
claim

**Comment by DikshantK2004** [comment]
claim
