### ISSUE TITLE
Create Home Routes

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#21]
### Implement Home Endpoints

Create Endpoints
   - [x] **Endpoint:** GET /api/scoop/home/top
   - **Description:** Retrieve the top 5 news sorted based on the most number of upvotes on news.

   - [x] **Endpoint:** GET /api/scoop/home/credible
   - **Description:** Retrieve the latest news of the top 5 profiles sorted based on the most number of upvotes on profiles.

   - [x] **Endpoint:** GET /api/scoop/home/categories
   - **Description:** Return an array of all tags used in all news without duplicate entries.

   - [ ]**Endpoint:** GET /api/scoop/home/latest
   - **Description:** Retrieve the 5 latest news.

## Additional Information
- **Error Handling:**
  - Ensure robust error handling for each endpoint, providing clear and informative error messages (use the responseCodes in utils directory).

- **Data Validation:**
  - Validate incoming data to ensure it meets expected formats and constraints.
  - Handle edge cases gracefully and provide appropriate responses.

- **Testing:**
- Make sure you have tested the endpoints before sending a pull request.

- **Consistency:**
  - Ensure a consistent response format across all endpoints.
  - Maintain consistency in naming conventions and coding style.

- **Maintainability:**
  - Implement code in a modular and maintainable way for future updates.

**Comment by DikshantK2004** [comment]
Claim

**Comment by Vihaan-19** [comment]
@DikshantK2004 Assigned.

**Comment by rnavaneeth992** [comment]
claim

**Comment by chiragmalik2612** [comment]
still open? claim
