### ISSUE TITLE
Create Comment Routes

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#22]
## Description
I would like to request the addition of new API endpoints for managing comments on news articles:

- [ ]  **Endpoint:** GET /api/scoop/:scoopId/comments
   - **Description:** Get comments for a news article.
   - **Authentication Required:** Yes

- [ ] **Endpoint:** POST /api/scoop/:scoopId/comments
   - **Description:** Add a new comment to a news article.
   - **Authentication Required:** Yes

- [ ]  **Endpoint:** PATCH /api/scoop/:scoopId/comments/:commentId
   - **Description:** Edit a comment.
   - **Authentication Required:** Yes

## Additional Requirements
- **Error Handling:**
  - Use the responseCodes in utils directory for code consistency.

- **Security Considerations:**
  - Ensure proper authentication and authorization mechanisms are in place for authenticated endpoints.

- **Data Validation:**
  - Validate incoming data to ensure it meets expected formats and constraints.

- **Testing:**
  - Ensure you have tested the code before submitting a pull request.

- **Consistency:**
  - Ensure a consistent response format across all endpoints.
  - Maintain consistency in naming conventions and coding style.

**Comment by DikshantK2004** [comment]
Claim

**Comment by Vihaan-19** [comment]
@DikshantK2004 Assigned.

**Comment by rnavaneeth992** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by chiragmalik2612** [comment]
still open? claim
