### ISSUE TITLE
Verify Token Signature in Backend Controller

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#26]
# Issue: Verify Token Signature in Backend Controller

### Problem

We currently lack a backend controller to verify the signature of user tokens. Verifying the token signature is crucial for ensuring the integrity and authenticity of the token. Make necessary routes required for it

### Goal

Implement a backend controller that verifies the signature of user tokens.

## Tasks

1. **Create Backend Controller:**
   - Implement a new backend controller dedicated to verifying the signature of user tokens.

2. **Token Input:**
   - Ensure that the controller accepts a user token as input, typically sent in the request headers or body.

3. **Verify Token Signature:**
   - Implement logic to verify the signature of the user token.

4. **Error Handling:**
   - Implement proper error handling for cases where the token signature verification fails.

**Deadline: 24 hours**
## Additional Information

If you have any questions or need clarification, feel free to comment on this issue.

Thank you for your contribution!

**Comment by Jarviss77** [comment]
Claim

**Comment by Harshal5167** [comment]
Claim

**Comment by captainflatbelly** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by 0mBudsMan** [comment]
congrats @Jarviss77
