### ISSUE TITLE
Create PATCH Route for Updating User Details 

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#27]
# Issue: Create PATCH Route for Updating User Details

### Problem

We need to implement a backend functionality that takes a user token as input, generates user details from the token, locates the corresponding user in the database, and updates their information.

### Goal

The goal is to allow users to update their details securely by providing a token for verification.

## Tasks

1. **Create PATCH Route:**
   - Implement a new PATCH route in the backend for updating user details.

2. **Token Input:**
   - Ensure that the route accepts a user token as input, typically sent in the request headers or body.

3. **Generate User Details:**
   - Implement logic to generate user details (userid to be precise) using the provided token.

4. **Locate User in Database:**
   - Query the database to find the user based on that userid.

5. **Update User Details:**
   - Update the user's information in the database.

6. **Error Handling:**
   - Implement proper error handling for cases where the token is invalid or the user is not found.

## Additional Information

If you have any questions or need clarification, feel free to comment on this issue. Get this done in 24 hours

Thank you for your contribution!

**Comment by TheDivineAurora** [comment]
claim

**Comment by kushal7201** [comment]
Claim
