### ISSUE TITLE
Create Auth Middleware

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#4]
Our webpage requires an authentication middleware to ensure that the user is authenticated, which is required for several routes
(refer README.md).
- [ ] Implement a module to generate JWT tokens upon successful user authentication.
- [ ] Include essential user information in the token payload.
- [ ] Develop middleware function to verify JWT tokens for routes that require authentication.
- [ ] Ensure the middleware is modular and can be easily integrated into relevant routes.
- [ ] Include meaningful error messages for better debugging.

**Comment by Harshal5167** [comment]
claim

**Comment by Vihaan-19** [comment]
@Harshal5167 Assigned.

**Comment by coderatiiita** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by prernaa23** [comment]
claim

**Comment by 0mBudsMan** [comment]
Status?
