### ISSUE TITLE
Create Admin Middleware

### ISSUE THREAD

**Issue by Vihaan-19** [opencodeiiita/Scoop-Backend#5]
Create a new middleware, isAdmin, to check if a user has admin privileges. This middleware will be essential for controlling access to admin-specific routes and functionalities.
- If the user is an admin, allow the request to proceed; otherwise, return a 403 status with an appropriate error message.

- [x] The isAdmin middleware is created to check admin privileges based on the user model.
- [x] Error handling is implemented for non-admin users attempting to access admin-specific routes.

**Comment by Nivedh-Biju** [comment]
claim

**Comment by coderatiiita** [comment]
claim

**Comment by 0mBudsMan** [comment]
Congrats Nivedh-Biju!
