### ISSUE TITLE
Implement Controllers and Routes for Fetching Top and Credible Scoop

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#6]
## Issue Title:
"Implement Controllers and Routes for Fetching Top and Credible Scoop" (Refer already created model for schema)

### Objective:
Implement controllers and routes to handle requests for fetching top scoop (news) and credible scoop based on user profiles.

#### Task 1: Fetching Top Scoop
1. **Description:**
   Create a controller and route that fetches top scoop (news) from the database, sorted according to the most number of upvotes.

2. **Acceptance Criteria:**
   - The route should invoke the corresponding controller for fetching top scoop.
   - Ensure that the response includes the sorted list of news articles based on the most upvotes.

#### Task 2: Fetching Credible Scoop
1. **Description:**
   Create a controller and route that fetches credible scoop (news) from the database, sorted according to the latest news from users with the highest upvotes.

2. **Acceptance Criteria:**
   - The route should invoke the corresponding controller for fetching credible scoop.
   - Verify that the response includes the latest news articles from users with the highest upvotes in their profiles.

### Additional Information:

- Use the existing models and database schema for news articles and user profiles.
- Ensure error handling in case of database queries or other issues.
- The controllers and routes should be integrated with the existing Express.js application.
- Test the controller by feeding dummy data into your database,and attach those details along with your PR.

**Comment by coderatiiita** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by 0mBudsMan** [comment]
Congrats Shubham! Ensure the issue gets done in 36 hours! Do ping any mentor on discord for any issues! Happy coding :)

**Comment by 0mBudsMan** [comment]
> claim
These are the routes (all routes present in readme)
### General Routes:
- `GET /api/scoop/top`: Sort all news according to most number of upvotes
- `GET /api/scoop/credible`: Sort news according to highest upvotes in the profile of the user who uploaded it

**Comment by prernaa23** [comment]
claim
