### ISSUE TITLE
Implement Controllers and Routes for Fetching Latest News

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Backend#7]
## Issue Title:
"Implement Controllers and Routes for Fetching Latest News"

### Objective:
Create controllers and routes to handle requests for fetching the latest news from the database, sorted by date.

###Time Limit : 24 hours

#### Task 1: Fetching Latest News
1. **Description:**
   Create a controller and route that fetches the latest news articles from the database, sorted by date.

2. **Acceptance Criteria:**
   - The route should invoke the corresponding controller for fetching the latest news.
   - Ensure that the response includes the list of news articles sorted by date, with the latest articles appearing first.

### Additional Information:

- Use the existing models and database schema for news articles.
- Consider the format of the date in the response (e.g., ISO format).
- Ensure error handling in case of database queries or other issues.
- Integrate the controllers and routes with the existing Express.js application.
- Test the same by feeding dummy data in your database

**Comment by kushal7201** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by amanrubey** [comment]
Claim

**Comment by DikshantK2004** [comment]
claim

**Comment by samarthsm1100** [comment]
Claim

**Comment by svrks-boop** [comment]
claim
